### ISSUE TITLE
UI Funktionalität implementieren

### ISSUE THREAD

**Issue by superolelli** [hpi-swa-teaching/SWT18-Project-14#23]
Für ein an die UI übergebenes Wort, sollen folgende Möglichkeiten von der UI angeboten werden:
- ignore
- add to dictionary
- richtig geschriebene Alternative auswählen

**Comment by superolelli** [comment]
Ein Wort kann jetzt an die UI übergeben werden. Ignore und add-to-dictionary funktioniert.

**Comment by youri-k** [comment]
Closed with #26
