### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by WorldofJARcraft** [hpi-swa-teaching/SWT18-Project-14#64]
Windows is currently not supported.
Find or compile a Hunspell DLL, add it to the Windows libraries folder, and test if it works with FFI.

**Comment by rschwanhold** [comment]
We already had windows support a year ago. 
I don't remember where we got the dll's from, but I think these are the ones that we used:
[libhunspell_libs.zip](https://github.com/hpi-swa-teaching/SpellChecking/files/3096389/libhunspell_libs.zip)

**Comment by WorldofJARcraft** [comment]
Thank you. It works on my windows machine (again).
Branch: fix-libraries-windows.
